------------------------------------------- user  = ziv email = <north780316@gamil.com>
[Description]
	update VC script

[Commit Files]
	vc

diff --git a/vc b/vc
--- a/vc
+++ b/vc
@@ -10,12 +10,65 @@ msg_error ()
 {
 	msg=$1
 	echo "[vc error] $msg"
+	exit 1
 }
 
 msg_warn ()
 {
 	msg=$1
 	echo "[vc warn] $msg"
+}
+
+commit_with_changelog ()
+{
+	echo "[Start]"
+	user_name=`git config --get user.name`
+	user_email=`git config --get user.email`
+	tempfile=`mktemp /tmp/vc.XXXXXXXX`
+	if [ $? -ne 0 ]; then
+		msg_error "create tempfile fail"
+	fi
+
+	# redirect to tempfile and produce template
+	pid=$$ 
+	origin_fd_1_file=$(readlink /proc/$pid/fd/1)
+	if [ $? -ne 0 ]; then
+		msg_error "readlink fail"
+	fi
+
+	echo "redirect PID=$pid stdout from $origin_fd_1_file --> $tempfile"
+	exec 1>$tempfile
+	if [ $? -ne 0 ]; then
+		msg_error "redirect $origin_fd_1_file --> $tempfile fail"
+	fi
+	echo "-------------------------------------------"
+	echo "user  = ${user_name}"
+	echo "email = ${user_email}"
+	echo "[Description]"
+	echo ""
+	echo "[Commit Files]"
+	echo ""
+	exec 1>>$origin_fd_1_file
+	echo "redirect stdout from $tempfile --> $origin_fd_1_file"
+	if [ $? -ne 0 ]; then
+		msg_error "redirect $tempfile --> $origin_fd_1_file fail "
+	fi
+
+	# modify change log
+	vim $tempfile
+
+	# confirm commit
+	printf "[Confirm] commit (Y/N) ? "
+	read -n 1 response
+	if [ $response == "Y" -o $response == "y" ]; then
+		echo -e "\nCommit ..."
+		git commit -F $tempfile
+	else
+		echo -e "\nAbort"
+	fi
+
+	# clean-up
+	rm $tempfile
 }
 
 msg_info "arguments: $@"
@@ -26,13 +79,12 @@ options=$(getopt -o vhs: --long version,status: -- "$@")
 return_val=$?
 if [ $return_val -ne 0 ]; then
 	msg_error "parse command line arguments fail (return $return_val)"
-	exit 1
 fi
 
 
 msg_info "options: $options" # -- mean end of options, it will not process by eval set
 
-# convert options to $1, $2 ...
+# set -- assign $options to $1, $2 ...
 eval set -- "$options" 
 
 while true; do
@@ -61,3 +113,4 @@ while true; do
 	shift # move $1 to next argument
 done
 
+commit_with_changelog 
